---
- hosts: docker
  tasks:
  - name: create directory
    file:
      path: /root/work
      state: directory
      owner: root
      mode: 0755

  - name: copy file
    copy:
      src: playbook.yml
      dest: /root/work/playbook.yml
      owner: root
      mode: 0644
